#!/usr/bin/env ruby

bad_words = /
  \b
  (
    ass(hole)?|arse|ba+stard|bi+tch|(god)?da+mn|(mother)?fu+ck(er)?|shi+t(ty)?|put[ao]+
  )
  (es|s)?
  \b
/ix

if ARGV.first =~ bad_words
  require 'redis'
  redis = Redis.new(db: 7)
  last_key = 'cbot:potty_mouth:last_at'
  counter_key = 'cbot:potty_mouth:counter'

  redis.incr(counter_key)

  last_at = redis.get(last_key)
  diff = if last_at
    (Time.now - Time.at(last_at.to_i)).to_i
  else
    0
  end

  since = if diff < 60
    "#{diff} second#{diff != 1 ? 's': ''}"
  elsif (mins_since = (diff / 60)) < 60
    "#{mins_since} minute#{mins_since != 1 ? 's': ''}"
  elsif (hours_since = (mins_since / 60)) < 24
    "#{hours_since} hour#{hours_since != 1 ? 's' : ''}"
  else
    days_since = hours_since / 24
    "#{days_since} day#{days_since != 1 ? 's' : ''}"
  end

  puts ":wc: This chat has been profanity free for: #{since} (#{redis.get(counter_key)} incidents reported)"

  redis.set(last_key, Time.now.to_i)
end
