#!/usr/bin/env bash

set -o errexit

cd "$(./app-directory $1)"

git fetch --all --quiet
tag1="$(git tag --list production-us-* | tail -2 | head -1)"
tag2="$(git tag --list production-us-* | tail -1)"
url="https://github.com/MaxiMobility/$name/compare/$tag1...$tag2"

echo "This is new on production: $url"
