#!/usr/bin/env ruby

# Borrowed from: https://raw.githubusercontent.com/OtpChatBot/Ybot/master/plugins/decide.rb
#
# Ybot decision helper plugin
# Usage: Ybot decide foo bar
#

if ARGV.length != 1
    puts 'Wrong argument\nUsage: cbot decide foo bar'
    exit
end

options = ARGV[0].split(' ')

puts 'Definitely: ' + options[rand(options.length)]
