#!/usr/bin/env ruby

# Borrowed from: https://raw.githubusercontent.com/OtpChatBot/Ybot/master/plugins/decide.rb

if ARGV.length == 0
  puts 'Usage: cbot decide foo, bar, or foobar'
  exit
end

PREFIXES = ['Definitely', 'For sure', 'Obviously', 'Clearly', 'It has been decided:']
EXCLUDED = /\bor\b|\bbetween\b|,/

choices = ARGV.join(' ').split(/\bor\b|,/).map{ |w| w.gsub(EXCLUDED, '').strip }.reject { |w| w == '' }
choices = choices.first.split if choices.length == 1

puts "#{PREFIXES.sample} '#{choices.sample}'"
