#!/usr/bin/env ruby

require 'redis'

class Karma
  def initialize(nickname)
    @nickname = nickname
  end

  def incr
    karma = redis.incr redis_key
    puts "Increased karma for #{@nickname}. New karma is #{karma}"
  end

  def get
    karma = redis.get redis_key
    puts "Karma for #{@nickname} is #{karma || 0}"
  end

  private

  def redis
    @redis ||= Redis.new
  end

  def redis_key
    ["cbot", "karma", normalized_nickname].join(":")
  end

  def normalized_nickname
    @nickname.downcase.sub(/^@/, "")
  end
end

cmd, nickname = ARGV
unless %w[incr get].include?(cmd) && nickname && !nickname.empty?
  puts "Usage: cbot karma [incr|get] <nickname>"
  exit
end

Karma.new(nickname).send(cmd)
