#!/usr/bin/env ruby

require_relative 'karma'

cmd, nickname = ARGV
if %w[incr decr score rank rem].include?(cmd) && nickname && !nickname.empty?
  Karma.new(nickname).send(cmd)
elsif %w[winners losers range].include?(cmd)
  Karma.new.send(cmd)
else
  puts "```"
  puts "Usage:"
  puts "  cbot karma [incr|decr|score|rank] <nickname>"
  puts "  cbot karma [winners|losers]"
  puts "```"
end
