#!/home/maxi/.rvm/rubies/ruby-2.0.0-p247/bin/ruby

APP_NAMES = {
  nil                  => "cabify_server",
  "rails"              => "cabify_server",
  "cabify_server"      => "cabify_server",
  "node"               => "cabify_server_node",
  "cabify_server_node" => "cabify_server_node"
}

VALID_APP_NAMES = APP_NAMES.keys.compact.uniq

app_name = APP_NAMES.fetch(ARGV.first, ARGV.first)

unless VALID_APP_NAMES.include?(app_name)
  $stderr.puts "Invalid app name #{app_name.inspect}. Valid app names are #{VALID_APP_NAMES.join(", ")}"
  exit(1)
end

puts app_name
