#!/usr/bin/env bash
set -o errexit

if [ "$#" -ne 1 ]; then
  echo "Please provide <branch>"
  exit 1
fi

# assign variables from args
branch=$1

#echo "QA team is so lazy that we have a special command for them"
./deploy cabify_server staging-us $branch
