#!/usr/bin/env ruby

require "redis"

class QA
  Blocked = Class.new(StandardError)

  def block
    redis.set "cbot:qa:blocked", "true"
  end

  def unblock
    redis.del "cbot:qa:blocked"
  end

  def deploy(branch_name)
    raise Blocked if blocked?

    sanitize! branch_name

    IO.popen "./deploy cabify_server staging-us #{branch_name}" do |f|
      until f.eof?
        s = f.gets
        yield s if block_given?
      end
    end
  end

  private

  def sanitize!(branch_name)
    unless branch_name =~ /\A[-\w]+\z/
      raise "I wouldn't do that if I were you"
    end
  end

  def blocked?
    redis.get("cbot:qa:blocked") == "true"
  end

  def redis
    @redis ||= Redis.new
  end
end

branch_name = ARGV.first
qa = QA.new

case branch_name
when "block", "unblock"
  qa.send(branch_name)
  puts "QA has been #{branch_name}ed"
when nil, ""
  puts "    Usage:"
  puts "      cbot qa [block|unblock]"
  puts "      cbot qa <branch_name>"
else
  begin
    qa.deploy branch_name { |s| puts s }
  rescue QA::Blocked
    puts "Cannot deploy to staging, it is blocked!"
  end
end
