#!/usr/bin/env ruby

require 'net/http'

uri  = URI('http://thecodinglove.com/random')
res  = Net::HTTP.get_response(uri)
uri  = URI(res['Location'])
res  = Net::HTTP.get_response(uri)

html = res.body

if html =~ %r{<h3><a href="[^"]+">([^<]+)</a></h3> </div> <div class="bodytype"> <p class="\w+"><img( alt="image")? src="([^"]+)"/><br/><i>[^<]+</i></p>}
  puts $1
  puts $3
else
  puts "ooops, couldn't find an image in #{uri}!"
end
