#!/usr/bin/env ruby

require 'net/http'
require 'open-uri'
require 'nokogiri'

uri  = URI('http://thecodinglove.com/random')
res  = Net::HTTP.get_response(uri)
uri  = URI(res['Location'])

begin
  html = open uri
  doc = Nokogiri::HTML html
  title = doc.css('h3 a').text
  img   = doc.css('.bodytype img').attr('src').value
  puts title
  puts img
rescue => e
  puts "ooops, could not get an image in #{uri}. #{e.message}"
end
