#!/usr/bin/env bash
set -o errexit

export GOPATH=/home/maxi/cbot/
# cbot repo
dir=/home/maxi/cbot/src/bitbucket.org/cabify/cbot
branch="master"

cd $dir

# fetch any new branches
git fetch --all --quiet
# switch to branch
git checkout $branch --quiet 
# update to state of remote branch
git reset --hard origin/$branch --quiet 

make > /dev/null

echo "Updated myself"
# reboot cbot in background
at now < /dev/null 2&>1 << EOF
sudo stop cbot || true && sleep 1 && sudo cp $dir/bin/linux-386/cbot /usr/local/bin/cbot && sudo start cbot
EOF 
