#!/usr/bin/env bash
set -o errexit

export GOPATH=/opt/cbot/
# cbot repo
dir=$(cd ..; pwd)
branch="master"

cd $dir

# fetch any new branches
git fetch --all --quiet
# switch to branch
git checkout $branch --quiet
# update to state of remote branch
git reset --hard origin/$branch --quiet

make > /dev/null

echo "Updated myself, like a boss :underage:"
# reboot cbot in background
at now 2> /dev/null <<EOF
sleep 1
sudo stop cbot || true && sleep 1 && sudo start cbot
EOF
