#!/usr/bin/env ruby
#
# Borrowed from: https://raw.githubusercontent.com/OtpChatBot/Ybot/master/plugins/wat.rb
#

require 'net/http'
require 'json'

uri = URI('http://watme.herokuapp.com/random')
res = Net::HTTP.get_response(uri)

# get url
result = JSON.parse(res.body)

# return url
puts result["wat"]
