#!/home/maxi/.rvm/rubies/ruby-2.0.0-p247/bin/ruby
#
# Borrowed from: https://raw.githubusercontent.com/OtpChatBot/Ybot/master/plugins/wat.rb
#
#
# Ybot WAT plugin
# Usage: Ybot wat
#

require 'net/http'
require 'json'

uri = URI('http://watme.herokuapp.com/random')
res = Net::HTTP.get_response(uri)

# get url
result = JSON.parse(res.body)

# return url
puts result["wat"]
