#!/usr/bin/env ruby

require 'net/http'
require 'json'

def what_day_is_it_today?
  wday = Time.now.wday
  if wday == 5
    uri = URI('https://ajax.googleapis.com/ajax/services/search/images')
    uri.query = URI.encode_www_form(v: "1.0", safe: "active", rsz: "8", q: "it's friday")
    res = Net::HTTP.get_response(uri)

    # get url
    result = JSON.parse(res.body)

    # return url
    puts "It is Friday!"
    puts result["responseData"]["results"].sample["url"]
  else
    wdays = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    puts "It is #{wdays[wday]} :("
  end
end

def what_are_your_rules?
  puts "I may not injure a human being or, through inaction, allow a human being to come to harm."
  puts "I must obey the orders given to me by human beings, except where such orders would conflict with the First Law."
  puts "I must protect my own existence as long as such protection does not conflict with the First or Second Law."
end

question = ARGV.join(" ").downcase
question << "?" unless question.end_with?("?")

case question
when "is the answer to the ultimate question of life, the universe, and everything?"
  puts "42"
when "are your rules?"
  what_are_your_rules?
when "day is it?", "day is it today?"
  what_day_is_it_today?
when %r{is (in|on) staging( (in|on) (?<app_name>\w+))?\?}
  puts `./whats-on-staging #{$~[:app_name]}`
when %r{is (new|changed)( on (?<app_name>\w+))?\?}
  puts `./changeset #{$~[:app_name]}`
when "happened?", "happens?"
  puts `./bofh`
else
  puts "I don't know, my creators didn't teach me :("
end
