#!/usr/bin/env bash

set -o errexit

app=$(./helpers/normalize-app-name $1)
appDir=$(cd ../deployables/$app; pwd)

cd $appDir

git fetch --all --quiet
tag1="$(git tag --list production-20* | tail -2 | head -1)"
tag2="$(git tag --list production-20* | tail -1)"
url="https://github.com/MaxiMobility/$app/compare/$tag1...$tag2"

echo "This is new on production: $url"
