#!/usr/bin/env bash

set -o errexit

app=$(./helpers/normalize-app-name $1)

cd "/home/maxi/cbot/$app"

current_branch="$(git rev-parse --abbrev-ref HEAD)"

echo "The current branch on test.cabify.com is $current_branch"
